invoice/urls.py
from django.conf.urls import url
from . import views

app_name = 'invoicemanager'

urlpatterns = [

    url(r'^$', views.invoices.index, name='index'),

    # INVOICES
    url(r'^invoice/new/$', views.invoices.new_invoice, name='new_invoice'),
    url(r'^invoice/all/$', views.invoices.all_invoices, name='all_invoices'),
    url(r'^invoice/draft/$', views.invoices.draft_invoices, name='draft_invoices'),
    url(r'^invoices/invalid/$', views.invoices.invalid_invoices, name='invalid_invoices'),
    url(r'^invoice/paid/$', views.invoices.paid_invoices, name='paid_invoices'),
    url(r'^invoice/unpaid/$', views.invoices.unpaid_invoices, name='unpaid_invoices'),
    url(r'^invoice/(?P<invoice_id>[0-9]+)/$', views.invoices.invoice, name='invoice'),
    url(r'^invoice/search/$', views.invoices.search_invoice, name='search_invoice'),
    url(r'^view-invoice/(?P<invoice_id>[0-9]+)/$', views.invoices.view_invoice, name='view_invoice'),
    url(r'^invoice/(?P<invoice_id>[0-9]+)/print/$', views.invoices.print_invoice, name='print_invoice'),
    url(r'^invoice/(?P<invoice_id>[0-9]+)/invalidate/$', views.invoices.invalidate_invoice, name='invalidate_invoice'),

    # ITEMS
    url(r'^invoice/(?P<invoice_id>[0-9]+)/item/add/$', views.items.add_item, name='add_item'),
    url(r'^invoice/(?P<invoice_id>[0-9]+)/item/(?P<invoiceitem_id>[0-9]+)/delete/$', views.items.delete_item, name='delete_item'),

    # CUSTOMERS
    url(r'^customers/$', views.customers.customer_list, name='customer_list'),
    url(r'^customer/(?P<customer_id>[0-9]+)/$', views.customers.customer, name='customer'),
    url(r'^customer/(?P<customer_id>[0-9]+)/update/$', views.customers.update_customer, name='update_customer'),
    url(r'^customer/(?P<customer_id>[0-9]+)/delete/$', views.customers.delete_customer, name='delete_customer'),
    url(r'^customer/new/$', views.customers.new_customer, name='new_customer'),
]

invoicemanager/urls.py
# Third party apps.
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

# Local application imports
from .routers import router

urlpatterns = [
    url(r'^', include('users.urls', namespace="users")),
    url(r'^invoice/', include('invoice.urls', namespace="invoice")),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^all_invoices/$',
        TemplateView.as_view(template_name='invoice/vuejs_all_invoices.html'),
        name='vue_all_invoices'),
]

users/urls.py
from django.conf.urls import url

from users.views.login_view import sign_in
from users.views.logout_view import sign_out
from users.views.registration_view import registration

urlpatterns = [
    url(r'^registration/$', registration, name="registration"),
    url(r'^$', sign_in, name="login"),
    url(r'^logout/$', sign_out, name="logout"),
]

templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">

<head>
	<link rel="icon" href="{% static 'invoice/img/favicon.png' %}" type="image/gif" >

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	{% if title %}
	<title>mPedigree Invoice Manager | {{ title }}</title>
	{% else %}
	<title>mPedigree Invoice Manager</title>
	{% endif %}
	{% block stylesheets %}
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="{% static 'invoice/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'invoice/js/bootstrap-datepicker.min.js' %}"></script>

	<link rel="stylesheet" type="text/css" href="{% static 'invoice/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'invoice/css/bootstrap-theme.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'invoice/css/bootstrap-datepicker.min.css' %}">
	{% endblock stylesheets %}
</head>

<body>
	<nav class="navbar navbar-inverse navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="{% url 'invoice:index' %}"><strong>mPedigree</strong> Invoice <strong>Manager</strong></a>
			</div>

			{% if user.is_authenticated %}

			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Invoices <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'invoice:new_invoice' %}"><strong>New Invoice</strong></a></li>
							<li><a href="{% url 'invoice:index' %}">Recent</a></li>
							<li class="divider" role="separator"></li>
							<li><a href="{% url 'invoice:all_invoices' %}">List All</a></li>
                            <li><a href="{% url 'vue_all_invoices' %}">Vuejs All Invoices List</a></li>
							<li><a href="{% url 'invoice:invalid_invoices' %}">Invalid Invoices</a></li>
							<li><a href="{% url 'invoice:draft_invoices' %}">Draft Invoices</a></li>
							<li><a href="{% url 'invoice:paid_invoices' %}">Paid Invoices</a></li>
							<li><a href="{% url 'invoice:unpaid_invoices' %}">Unpaid Invoices</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Customers <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'invoice:new_customer' %}"><strong>New Customer</strong></a></li>
							<li role="separator" class="divider"></li>
							<li><a href="{% url 'invoice:customer_list' %}">List All</a></li>
						</ul>
					</li>
				</ul>

				<form class="navbar-form navbar-right" action="{% url 'invoice:search_invoice' %}" method="POST">
					{% csrf_token %}
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Invoice Number" name="id">
					</div>
					<button type="submit" class="btn btn-default">Go</button>
				</form>

				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Hello, {{ user.username }} <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a href="{% url 'users:logout' %}"><strong>Logout</strong></a></li>
							</ul>
					</li>
				</ul>
			</div>

			{% endif %}

		</div>
	</nav>

	<div class="container">
			{% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}

{% block content %}

{% endblock %}

	</div>
</body>

</html>